import { FieldDefinition } from "../../common/field-definition";

export const PNL_V1_SKU_FIELDS: FieldDefinition[] = [
  // Identity
  {
    key: "sku",
    label: "SKU ID",
    aliases: ["SKU ID", "SKU", "SKU Name", "Seller SKU", "Product SKU", "SKU_ID"],
    type: "string",
    importance: "required",
    required: true,
    description: "Unique seller stock keeping unit identifier.",
    sourceReports: ["profit_loss"],
  },

  // Units
  {
    key: "grossUnits",
    label: "Gross Units",
    aliases: ["Gross Units (#)", "Gross Units", "Total Units", "Units Sold"],
    type: "integer",
    importance: "required",
    required: true,
    description: "Total units ordered by customers prior to cancellations/returns.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "returnedCancelledUnits",
    label: "Returned & Cancelled Units",
    aliases: [
      "Returned & Cancelled Units",
      "Returned & Cancelled",
      "Returned and Cancelled Units",
      "Ret + Canc Units",
    ],
    type: "integer",
    importance: "required",
    required: false,
    description: "Aggregated count of returned, cancelled, and logistics failure units.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "rtoUnits",
    label: "RTO Units",
    aliases: ["RTO (Logistics Return)", "RTO", "Logistics Return", "RTO Units"],
    parentAliases: ["Returned & Cancelled Units (Breakup)"],
    type: "integer",
    importance: "optional",
    required: false,
    description: "Return to Origin (courier delivery failure) units.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "rvpUnits",
    label: "RVP Units",
    aliases: ["RVP (Customer Return)", "RVP", "Customer Return", "RVP Units"],
    parentAliases: ["Returned & Cancelled Units (Breakup)"],
    type: "integer",
    importance: "optional",
    required: false,
    description: "Reverse Pickup (customer-initiated return) units.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "cancelledUnits",
    label: "Cancelled Units",
    aliases: ["Cancellations", "Cancelled Units", "Cancelled"],
    parentAliases: ["Returned & Cancelled Units (Breakup)"],
    type: "integer",
    importance: "optional",
    required: false,
    description: "Orders cancelled prior to shipment.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "netUnits",
    label: "Net Units",
    aliases: ["Net Units (#)", "Net Units", "Net Unit", "Delivered Units"],
    type: "integer",
    importance: "required",
    required: true,
    description: "Gross Units minus Returned and Cancelled Units.",
    sourceReports: ["profit_loss"],
  },

  // Sales
  {
    key: "estimatedNetSales",
    label: "Estimated Net Sales",
    aliases: [
      "Estimated Net Sales (INR)",
      "Estimated Net Sales",
      "Estimated Sales",
      "Net Sales (INR)",
    ],
    type: "number",
    importance: "required",
    required: true,
    description: "Projected net sales value based on actual dispatched units.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "orderItemValue",
    label: "Sum of Order Item Value",
    aliases: ["Sum of Order Item Value", "Order Item Value", "Item Value", "Gross GMV"],
    type: "number",
    importance: "optional",
    required: false,
    description: "Gross order item values calculated before customer discounts.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "accountedNetSales",
    label: "Accounted Net Sales",
    aliases: [
      "Accounted Net Sales (Seller Price)",
      "Accounted Net Sales",
      "Seller Price",
      "Net Seller Price",
    ],
    type: "number",
    importance: "optional",
    required: false,
    description: "Realized net sales accounted at seller listed price.",
    sourceReports: ["profit_loss"],
  },

  // Total Expenses
  {
    key: "totalExpenses",
    label: "Total Expenses",
    aliases: ["Total Expenses (INR)", "Total Expenses", "Expenses", "Marketplace Fees"],
    type: "number",
    importance: "required",
    required: true,
    description: "Official Flipkart total marketplace expenses charged to seller.",
    sourceReports: ["profit_loss"],
  },

  // Expense Breakups (Row 2 Child Headers under "Total Expenses (Breakup)")
  {
    key: "commissionFee",
    label: "Commission Fee",
    aliases: ["Commission Fee", "Commission", "Marketplace Commission"],
    parentAliases: ["Total Expenses (Breakup)"],
    type: "number",
    importance: "optional",
    required: false,
    description: "Category percentage fee charged on selling price.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "collectionFee",
    label: "Collection Fee",
    aliases: ["Collection Fee", "Payment Collection Fee", "Payment Gateway Fee"],
    parentAliases: ["Total Expenses (Breakup)"],
    type: "number",
    importance: "optional",
    required: false,
    description: "Payment gateway and cash collection processing fee.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "fixedFee",
    label: "Fixed Fee",
    aliases: ["Fixed Fee", "Fixed Fee (INR)", "Fixed Charges", "Fixed Closing Fee"],
    parentAliases: ["Total Expenses (Breakup)"],
    type: "number",
    importance: "optional",
    required: false,
    description: "Tiered fixed fee per order item.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "pickAndPackFee",
    label: "Pick and Pack Fee",
    aliases: ["Pick and Pack Fee", "Pick & Pack Fee", "Pick Pack Fee", "Fulfillment Fee"],
    parentAliases: ["Total Expenses (Breakup)"],
    type: "number",
    importance: "optional",
    required: false,
    description: "Warehouse fulfillment handling fee.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "forwardShippingFee",
    label: "Forward Shipping Fee",
    aliases: ["Forward Shipping Fee", "Forward Shipping", "Shipping Fee", "Forward Logistics"],
    parentAliases: ["Total Expenses (Breakup)"],
    type: "number",
    importance: "optional",
    required: false,
    description: "Outbound logistics delivery fee.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "offerAdjustments",
    label: "Offer Adjustments",
    aliases: ["Offer adjustments", "Offer Adjustments", "Discount Adjustments"],
    parentAliases: ["Total Expenses (Breakup)"],
    type: "number",
    importance: "optional",
    required: false,
    description: "Promotional and co-funded offer adjustments.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "reverseShippingFee",
    label: "Reverse Shipping Fee",
    aliases: ["Reverse Shipping Fee", "Reverse Shipping", "Return Shipping Fee"],
    parentAliases: ["Total Expenses (Breakup)"],
    type: "number",
    importance: "optional",
    required: false,
    description: "Return logistics freight fee charged on customer returns.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "storageFee",
    label: "Storage Fee",
    aliases: ["Storage Fee", "Warehouse Storage Fee", "Storage Charges"],
    parentAliases: ["Total Expenses (Breakup)"],
    type: "number",
    importance: "optional",
    required: false,
    description: "Inventory storage fee in Flipkart Fulfillment Centers.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "recallFee",
    label: "Recall Fee",
    aliases: ["Recall Fee", "Inventory Recall Fee", "Removal Fee"],
    parentAliases: ["Total Expenses (Breakup)"],
    type: "number",
    importance: "optional",
    required: false,
    description: "Fee for recalling inventory back from fulfillment centers.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "noCostEmiFeeReimbursement",
    label: "No Cost EMI Fee Reimbursement",
    aliases: [
      "No Cost Emi Fee Reimbursement(Rs.)",
      "No Cost EMI Fee Reimbursement",
      "No Cost EMI",
    ],
    parentAliases: ["Total Expenses (Breakup)"],
    type: "number",
    importance: "optional",
    required: false,
    description: "Subvention fees for customer zero-interest EMI financing.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "installationFee",
    label: "Installation Fee",
    aliases: ["Installation Fee (Rs.)", "Installation Fee", "Installation Charges"],
    parentAliases: ["Total Expenses (Breakup)"],
    type: "number",
    importance: "optional",
    required: false,
    description: "At-home product installation fees.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "techVisitFee",
    label: "Tech Visit Fee",
    aliases: ["Tech Visit Fee (Rs.)", "Tech Visit Fee", "Technician Visit"],
    parentAliases: ["Total Expenses (Breakup)"],
    type: "number",
    importance: "optional",
    required: false,
    description: "Technician doorstep service fee.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "uninstallationPackagingFee",
    label: "Uninstallation & Packaging Fee",
    aliases: [
      "Uninstallation & Packaging Fee (Rs.)",
      "Uninstallation & Packaging Fee",
      "Packaging Fee",
    ],
    parentAliases: ["Total Expenses (Breakup)"],
    type: "number",
    importance: "optional",
    required: false,
    description: "Reverse packaging and uninstallation costs.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "customerAddonsRecovery",
    label: "Customer Add-ons Amount Recovery",
    aliases: [
      "Customer Add-ons Amount Recovery (Rs.)",
      "Customer Add-ons Amount Recovery",
      "Add-ons Recovery",
    ],
    parentAliases: ["Total Expenses (Breakup)"],
    type: "number",
    importance: "optional",
    required: false,
    description: "Recovery for complementary warranty or accessory add-ons.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "franchiseFee",
    label: "Franchise Fee",
    aliases: ["Franchise Fee (Rs.)", "Franchise Fee", "Franchise Charges"],
    parentAliases: ["Total Expenses (Breakup)"],
    type: "number",
    importance: "optional",
    required: false,
    description: "Franchise channel distribution fees.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "shopsyMarketingFee",
    label: "Shopsy Marketing Fee",
    aliases: ["Shopsy Marketing Fee (Rs.)", "Shopsy Marketing Fee", "Shopsy Fee"],
    parentAliases: ["Total Expenses (Breakup)"],
    type: "number",
    importance: "optional",
    required: false,
    description: "Shopsy reseller promotional marketing fee.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "productCancellationFee",
    label: "Product Cancellation Fee",
    aliases: ["Product Cancellation Fee (Rs.)", "Product Cancellation Fee", "Seller Cancellation Fee"],
    parentAliases: ["Total Expenses (Breakup)"],
    type: "number",
    importance: "optional",
    required: false,
    description: "Penalty fee charged for seller-initiated cancellations.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "taxesGst",
    label: "Taxes (GST)",
    aliases: ["Taxes (GST)", "GST", "Expense GST", "Taxes GST"],
    parentAliases: ["Total Expenses (Breakup)"],
    type: "number",
    importance: "optional",
    required: false,
    description: "Goods and Services Tax on marketplace fees (18%).",
    sourceReports: ["profit_loss"],
  },
  {
    key: "taxesTcs",
    label: "Taxes (TCS)",
    aliases: ["Taxes (TCS)", "TCS", "Expense TCS", "Taxes TCS"],
    parentAliases: ["Total Expenses (Breakup)"],
    type: "number",
    importance: "optional",
    required: false,
    description: "Tax Collected at Source (1%).",
    sourceReports: ["profit_loss"],
  },
  {
    key: "taxesTds",
    label: "Taxes (TDS)",
    aliases: ["Taxes (TDS)", "TDS", "Expense TDS", "Taxes TDS"],
    parentAliases: ["Total Expenses (Breakup)"],
    type: "number",
    importance: "optional",
    required: false,
    description: "Tax Deducted at Source (Section 194-O, 0.1% or 1%).",
    sourceReports: ["profit_loss"],
  },

  // Benefits
  {
    key: "totalBenefits",
    label: "Total Benefits",
    aliases: ["Rewards & Other Benefits (INR)", "Rewards & Other Benefits", "Total Benefits"],
    type: "number",
    importance: "optional",
    required: false,
    description: "Total rewards and SPF compensation credited to seller.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "rewards",
    label: "Rewards",
    aliases: ["Rewards", "Reward Earnings"],
    parentAliases: ["Rewards & Other Benefits(Breakup)", "Total Benefits (Breakup)"],
    type: "number",
    importance: "optional",
    required: false,
    description: "Performance incentives and promotional bonus rewards.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "orderSpf",
    label: "Order SPF",
    aliases: ["Order SPF", "SPF Payout", "SPF Claim"],
    parentAliases: ["Rewards & Other Benefits(Breakup)", "Total Benefits (Breakup)"],
    type: "number",
    importance: "optional",
    required: false,
    description: "Seller Protection Fund payout for damaged or lost returns.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "nonOrderSpf",
    label: "Non Order SPF",
    aliases: ["Non Order SPF", "Non-Order SPF", "General SPF"],
    parentAliases: ["Rewards & Other Benefits(Breakup)", "Total Benefits (Breakup)"],
    type: "number",
    importance: "optional",
    required: false,
    description: "Ad-hoc Seller Protection Fund compensation.",
    sourceReports: ["profit_loss"],
  },

  // Settlement & Taxes
  {
    key: "bankSettlement",
    label: "Bank Settlement [Projected]",
    aliases: [
      "Bank Settlement [Projected] (INR)",
      "Bank Settlement [Projected]",
      "Bank Settlement",
      "Projected Settlement",
    ],
    type: "number",
    importance: "optional",
    required: false,
    description: "Final projected payout credited to bank account.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "inputTaxCredits",
    label: "Input Tax Credits",
    aliases: ["Input Tax Credits (INR)", "Input Tax Credits", "Total ITC", "ITC Total"],
    type: "number",
    importance: "optional",
    required: false,
    description: "Input Tax Credits eligible to claim against GST filings.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "itcGstTcs",
    label: "ITC (GST + TCS)",
    aliases: ["GST + TCS", "ITC GST+TCS"],
    parentAliases: ["Input Tax Credits (Breakup)"],
    type: "number",
    importance: "optional",
    required: false,
    description: "GST and TCS tax credit component.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "itcTds",
    label: "ITC (TDS)",
    aliases: ["TDS", "ITC TDS"],
    parentAliases: ["Input Tax Credits (Breakup)"],
    type: "number",
    importance: "optional",
    required: false,
    description: "TDS tax credit component.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "netEarnings",
    label: "Net Earnings",
    aliases: ["Net Earnings (INR)", "Net Earnings", "Earnings", "Seller Profit"],
    type: "number",
    importance: "required",
    required: true,
    description: "Official Flipkart Net Earnings (Bank Settlement + Input Tax Credits).",
    sourceReports: ["profit_loss"],
  },
  {
    key: "earningsPerUnit",
    label: "Earnings per unit",
    aliases: ["Earnings per unit (INR)", "Earnings per unit", "Earnings Per Unit", "EPU"],
    type: "number",
    importance: "optional",
    required: false,
    description: "Average net earnings generated per delivered unit.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "amountSettled",
    label: "Amount Settled",
    aliases: ["Amount Settled (INR)", "Amount Settled", "Settled"],
    type: "number",
    importance: "optional",
    required: false,
    description: "Total funds successfully cleared and transferred via NEFT.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "amountPending",
    label: "Amount Pending",
    aliases: ["Amount Pending (INR)", "Amount Pending", "Pending"],
    type: "number",
    importance: "optional",
    required: false,
    description: "Outstanding funds scheduled for upcoming settlement cycle.",
    sourceReports: ["profit_loss"],
  },
];

export const PNL_V1_ORDERS_FIELDS: FieldDefinition[] = [
  // Order Identity
  {
    key: "orderId",
    label: "Order ID",
    aliases: ["Order ID", "OrderId", "Order Number", "Order_ID"],
    type: "string",
    importance: "required",
    required: true,
    description: "Unique Flipkart parent order identifier.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "orderItemId",
    label: "Order Item ID",
    aliases: ["Order Item ID", "OrderItemId", "Item ID", "Order_Item_ID"],
    type: "string",
    importance: "required",
    required: true,
    description: "Unique Flipkart order item identifier (Primary relationship key).",
    sourceReports: ["profit_loss"],
  },
  {
    key: "orderDate",
    label: "Order Date",
    aliases: ["Order Date", "Date", "Ordered Date", "Purchase Date"],
    type: "date",
    importance: "optional",
    required: false,
    description: "Date the customer placed the order on Flipkart.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "sku",
    label: "SKU Name",
    aliases: ["SKU Name", "SKU", "SKU ID", "Seller SKU", "Product SKU"],
    type: "string",
    importance: "required",
    required: true,
    description: "Stock keeping unit identifier for the item.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "fulfillmentType",
    label: "Fulfillment Type",
    aliases: ["Fulfillment Type", "FF Type", "Fulfilment", "Fulfillment Mode"],
    type: "string",
    importance: "optional",
    required: false,
    description: "Flipkart Assured (FA), Non-FA, or Direct seller fulfillment.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "channelOfSale",
    label: "Channel of Sale",
    aliases: ["Channel of Sale", "Channel", "Sale Channel"],
    type: "string",
    importance: "optional",
    required: false,
    description: "Marketplace channel (Flipkart, Shopsy, Grocery).",
    sourceReports: ["profit_loss"],
  },
  {
    key: "modeOfPayment",
    label: "Mode of Payment",
    aliases: ["Mode of Payment", "Payment Mode", "Payment Type"],
    type: "string",
    importance: "optional",
    required: false,
    description: "Prepaid UPI, Card, Net Banking, or Cash on Delivery (COD).",
    sourceReports: ["profit_loss"],
  },
  {
    key: "orderStatus",
    label: "Order Status",
    aliases: ["Order Status", "Status", "Item Status"],
    type: "string",
    importance: "required",
    required: true,
    description: "Current delivery/settlement status of the order item.",
    sourceReports: ["profit_loss"],
  },

  // Units
  {
    key: "grossUnits",
    label: "Gross Units",
    aliases: ["Gross Units", "Quantity", "Qty", "Gross Units (#)"],
    type: "integer",
    importance: "required",
    required: true,
    description: "Quantity of units ordered in this item line.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "returnedCancelledUnits",
    label: "Returned & Cancelled Units",
    aliases: ["Returned & Cancelled Units", "Returned & Cancelled"],
    type: "integer",
    importance: "optional",
    required: false,
    description: "Units returned or cancelled for this item.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "rtoUnits",
    label: "RTO Units",
    aliases: ["RTO (Logistics Return)", "RTO"],
    parentAliases: ["Returned & Cancelled Units (Breakup)"],
    type: "integer",
    importance: "optional",
    required: false,
    description: "Courier return units.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "rvpUnits",
    label: "RVP Units",
    aliases: ["RVP (Customer Return)", "RVP"],
    parentAliases: ["Returned & Cancelled Units (Breakup)"],
    type: "integer",
    importance: "optional",
    required: false,
    description: "Customer return units.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "cancelledUnits",
    label: "Cancelled Units",
    aliases: ["Cancelled Units", "Cancellations"],
    parentAliases: ["Returned & Cancelled Units (Breakup)"],
    type: "integer",
    importance: "optional",
    required: false,
    description: "Cancelled units.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "netUnits",
    label: "Net Units",
    aliases: ["Net Units", "Net Units (#)"],
    type: "integer",
    importance: "optional",
    required: false,
    description: "Delivered net units for this line.",
    sourceReports: ["profit_loss"],
  },

  // Sales
  {
    key: "orderItemValue",
    label: "Order Item Value",
    aliases: ["Order Item Value", "Item Value", "Price"],
    type: "number",
    importance: "optional",
    required: false,
    description: "Listing item value before discounts.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "finalSellingPrice",
    label: "Final Selling Price",
    aliases: ["Final Selling Price (FSP)", "Final Selling Price", "Selling Price", "FSP"],
    type: "number",
    importance: "required",
    required: true,
    description: "Actual listing selling price visible to customer.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "handlingFee",
    label: "Handling Fee",
    aliases: ["Handling Fee", "Customer Logistics Fee"],
    type: "number",
    importance: "optional",
    required: false,
    description: "Packaging/handling fee billed to customer.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "estimatedNetSales",
    label: "Estimated Net Sales",
    aliases: ["Estimated Net Sales (INR)", "Estimated Net Sales"],
    type: "number",
    importance: "optional",
    required: false,
    description: "Projected net sales for order item.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "accountedNetSales",
    label: "Accounted Net Sales",
    aliases: ["Accounted Net Sales (Seller Price)", "Accounted Net Sales", "Seller Price"],
    type: "number",
    importance: "optional",
    required: false,
    description: "Realized net sales credited at seller price.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "grossSaleValue",
    label: "Gross Sale Value",
    aliases: ["Gross Sale Value"],
    parentAliases: ["Accounted Net Sales (Seller Price) (Breakup)"],
    type: "number",
    importance: "optional",
    required: false,
    description: "Gross value component.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "sellerFundedDiscount",
    label: "Seller-Funded Discount",
    aliases: ["Seller-Funded Discount", "Seller Discount"],
    parentAliases: ["Accounted Net Sales (Seller Price) (Breakup)"],
    type: "number",
    importance: "optional",
    required: false,
    description: "Discount financed directly by seller.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "customerAddOnsAmount",
    label: "Customer Add-ons Amount",
    aliases: ["Customer Add-Ons Amount", "Customer Add-ons Amount"],
    parentAliases: ["Accounted Net Sales (Seller Price) (Breakup)"],
    type: "number",
    importance: "optional",
    required: false,
    description: "Customer paid amount for add-on warranties/services.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "totalCustomerDiscount",
    label: "Total Customer Discount",
    aliases: ["Total Customer Discount", "Customer Discount"],
    parentAliases: ["Offer Details"],
    type: "number",
    importance: "optional",
    required: false,
    description: "Total discount applied across marketplace and seller promotions.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "offerId",
    label: "Offer ID",
    aliases: ["Offer Id", "Offer ID"],
    parentAliases: ["Offer Details"],
    type: "string",
    importance: "informational",
    required: false,
    description: "Promotional campaign offer identifier.",
    sourceReports: ["profit_loss"],
  },

  // Total Expenses & Fee Breakup
  {
    key: "totalExpenses",
    label: "Total Expenses",
    aliases: ["Total Expenses (INR)", "Total Expenses", "Expenses"],
    type: "number",
    importance: "required",
    required: true,
    description: "Official Flipkart total marketplace expenses charged to seller.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "commissionFee",
    label: "Commission Fee",
    aliases: ["Commission Fee", "Commission"],
    parentAliases: ["Total Expenses (Breakup)"],
    type: "number",
    importance: "optional",
    required: false,
    description: "Marketplace referral commission.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "collectionFee",
    label: "Collection Fee",
    aliases: ["Collection Fee"],
    parentAliases: ["Total Expenses (Breakup)"],
    type: "number",
    importance: "optional",
    required: false,
    description: "Payment gateway and collection charges.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "fixedFee",
    label: "Fixed Fee",
    aliases: ["Fixed Fee", "Fixed Fee (INR)", "Fixed Charges"],
    parentAliases: ["Total Expenses (Breakup)"],
    type: "number",
    importance: "optional",
    required: false,
    description: "Order item fixed fee.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "pickAndPackFee",
    label: "Pick and Pack Fee",
    aliases: ["Pick and Pack Fee", "Pick & Pack Fee"],
    parentAliases: ["Total Expenses (Breakup)"],
    type: "number",
    importance: "optional",
    required: false,
    description: "Fulfillment handling fee.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "forwardShippingFee",
    label: "Forward Shipping Fee",
    aliases: ["Forward Shipping Fee", "Forward Shipping"],
    parentAliases: ["Total Expenses (Breakup)"],
    type: "number",
    importance: "optional",
    required: false,
    description: "Outbound logistics shipping fee.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "reverseShippingFee",
    label: "Reverse Shipping Fee",
    aliases: ["Reverse Shipping Fee", "Reverse Shipping"],
    parentAliases: ["Total Expenses (Breakup)"],
    type: "number",
    importance: "optional",
    required: false,
    description: "Reverse logistics shipping fee on customer returns.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "storageFee",
    label: "Storage Fee",
    aliases: ["Storage Fee"],
    parentAliases: ["Total Expenses (Breakup)"],
    type: "number",
    importance: "optional",
    required: false,
    description: "Storage charges.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "recallFee",
    label: "Recall Fee",
    aliases: ["Recall Fee"],
    parentAliases: ["Total Expenses (Breakup)"],
    type: "number",
    importance: "optional",
    required: false,
    description: "Inventory removal fee.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "productCancellationFee",
    label: "Product Cancellation Fee",
    aliases: ["Product Cancellation Fee (Rs.)", "Product Cancellation Fee"],
    parentAliases: ["Total Expenses (Breakup)"],
    type: "number",
    importance: "optional",
    required: false,
    description: "Cancellation penalty.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "noCostEmiFeeReimbursement",
    label: "No Cost EMI Fee Reimbursement",
    aliases: ["No Cost EMI Fee Reimbursement", "No Cost Emi Fee Reimbursement(Rs.)"],
    parentAliases: ["Total Expenses (Breakup)"],
    type: "number",
    importance: "optional",
    required: false,
    description: "Zero cost EMI subvention fee.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "installationFee",
    label: "Installation Fee",
    aliases: ["Installation Fee (Rs.)", "Installation Fee"],
    parentAliases: ["Total Expenses (Breakup)"],
    type: "number",
    importance: "optional",
    required: false,
    description: "Installation fee.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "techVisitFee",
    label: "Tech Visit Fee",
    aliases: ["Tech Visit Fee (Rs.)", "Tech Visit Fee"],
    parentAliases: ["Total Expenses (Breakup)"],
    type: "number",
    importance: "optional",
    required: false,
    description: "Tech visit charges.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "uninstallationPackagingFee",
    label: "Uninstallation & Packaging Fee",
    aliases: ["Uninstallation & Packaging Fee (Rs.)", "Uninstallation & Packaging Fee"],
    parentAliases: ["Total Expenses (Breakup)"],
    type: "number",
    importance: "optional",
    required: false,
    description: "Uninstallation fee.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "customerAddonsRecovery",
    label: "Customer Add-ons Amount Recovery",
    aliases: ["Customer Add-ons Amount Recovery (Rs.)", "Customer Add-ons Amount Recovery"],
    parentAliases: ["Total Expenses (Breakup)"],
    type: "number",
    importance: "optional",
    required: false,
    description: "Add-on recovery.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "franchiseFee",
    label: "Franchise Fee",
    aliases: ["Franchise Fee (Rs.)", "Franchise Fee"],
    parentAliases: ["Total Expenses (Breakup)"],
    type: "number",
    importance: "optional",
    required: false,
    description: "Franchise channel fee.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "shopsyMarketingFee",
    label: "Shopsy Marketing Fee",
    aliases: ["Shopsy Marketing Fee (Rs.)", "Shopsy Marketing Fee"],
    parentAliases: ["Total Expenses (Breakup)"],
    type: "number",
    importance: "optional",
    required: false,
    description: "Shopsy marketing fee.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "offerAdjustments",
    label: "Offer Adjustments",
    aliases: ["Offer adjustments", "Offer Adjustments"],
    parentAliases: ["Total Expenses (Breakup)"],
    type: "number",
    importance: "optional",
    required: false,
    description: "Offer adjustments.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "taxesGst",
    label: "Taxes (GST)",
    aliases: ["Taxes (GST)", "GST"],
    parentAliases: ["Total Expenses (Breakup)"],
    type: "number",
    importance: "optional",
    required: false,
    description: "GST on fees.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "taxesTcs",
    label: "Taxes (TCS)",
    aliases: ["Taxes (TCS)", "TCS"],
    parentAliases: ["Total Expenses (Breakup)"],
    type: "number",
    importance: "optional",
    required: false,
    description: "TCS tax.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "taxesTds",
    label: "Taxes (TDS)",
    aliases: ["Taxes (TDS)", "TDS"],
    parentAliases: ["Total Expenses (Breakup)"],
    type: "number",
    importance: "optional",
    required: false,
    description: "TDS tax.",
    sourceReports: ["profit_loss"],
  },

  // Benefits
  {
    key: "totalBenefits",
    label: "Total Benefits",
    aliases: ["Rewards & Other Benefits (INR)", "Rewards & Other Benefits", "Total Benefits"],
    type: "number",
    importance: "optional",
    required: false,
    description: "Total benefits and SPF.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "rewards",
    label: "Rewards",
    aliases: ["Rewards"],
    parentAliases: ["Total Benefits (Breakup)", "Rewards & Other Benefits(Breakup)"],
    type: "number",
    importance: "optional",
    required: false,
    description: "Promotional rewards.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "spfPayout",
    label: "SPF Payout",
    aliases: ["SPF Payout", "SPF Claim", "Order SPF"],
    parentAliases: ["Total Benefits (Breakup)", "Rewards & Other Benefits(Breakup)"],
    type: "number",
    importance: "optional",
    required: false,
    description: "SPF protection claim credit.",
    sourceReports: ["profit_loss"],
  },

  // Settlement
  {
    key: "bankSettlementProjected",
    label: "Bank Settlement [Projected]",
    aliases: ["Bank Settlement [Projected]", "Bank Settlement", "Projected Bank Settlement"],
    type: "number",
    importance: "optional",
    required: false,
    description: "Projected payout.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "inputTaxCredits",
    label: "Input Tax Credits",
    aliases: ["Input Tax Credits (INR)", "Input Tax Credits", "Total ITC"],
    type: "number",
    importance: "optional",
    required: false,
    description: "Input tax credit.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "itcGstTcs",
    label: "ITC (GST + TCS)",
    aliases: ["GST + TCS"],
    parentAliases: ["Input Tax Credits (Breakup)"],
    type: "number",
    importance: "optional",
    required: false,
    description: "GST and TCS ITC.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "itcTds",
    label: "ITC (TDS)",
    aliases: ["TDS"],
    parentAliases: ["Input Tax Credits (Breakup)"],
    type: "number",
    importance: "optional",
    required: false,
    description: "TDS ITC.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "netEarnings",
    label: "Net Earnings",
    aliases: ["Net Earnings (INR)", "Net Earnings", "Earnings"],
    type: "number",
    importance: "required",
    required: true,
    description: "Official Flipkart net earnings for this order item.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "amountSettled",
    label: "Amount Settled",
    aliases: ["Amount Settled (INR)", "Amount Settled", "Settled"],
    type: "number",
    importance: "optional",
    required: false,
    description: "Amount settled.",
    sourceReports: ["profit_loss"],
  },
  {
    key: "amountPending",
    label: "Amount Pending",
    aliases: ["Amount Pending (INR)", "Amount Pending", "Pending"],
    type: "number",
    importance: "optional",
    required: false,
    description: "Amount pending.",
    sourceReports: ["profit_loss"],
  },
];
