import { FieldDefinition } from "../../common/field-definition";

export const RETURNS_V1_FIELDS: FieldDefinition[] = [
  // 1. Identity & Location
  {
    key: "locationId",
    label: "Location ID",
    aliases: ["Location ID", "location_id", "LocationID", "Warehouse ID"],
    type: "string",
    importance: "optional",
    required: false,
    description: "Flipkart warehouse or hub location identifier.",
    sourceReports: ["returns"],
  },
  {
    key: "orderId",
    label: "Order ID",
    aliases: ["Order ID", "order_id", "OrderId", "Order Number"],
    type: "string",
    importance: "required",
    required: true,
    description: "Flipkart order identifier.",
    sourceReports: ["returns"],
  },
  {
    key: "orderItemId",
    label: "Order Item ID",
    aliases: ["Order Item ID", "order_item_id", "OrderItemId", "Item ID", "Order Item Id"],
    type: "string",
    importance: "required",
    required: true,
    description: "Unique Flipkart order item identifier (Primary relationship link to P&L).",
    sourceReports: ["returns"],
  },
  {
    key: "returnId",
    label: "Return ID",
    aliases: ["Return ID", "return_id", "ReturnId", "Return Number"],
    type: "string",
    importance: "required",
    required: true,
    description: "Unique return request ID.",
    sourceReports: ["returns"],
  },
  {
    key: "trackingId",
    label: "Tracking ID",
    aliases: ["Tracking ID", "tracking_id", "TrackingId", "AWB Number", "Waybill"],
    type: "string",
    importance: "optional",
    required: false,
    description: "Reverse courier tracking airway bill number.",
    sourceReports: ["returns"],
  },
  {
    key: "shipmentId",
    label: "Shipment ID",
    aliases: ["Shipment ID", "shipment_id", "ShipmentId"],
    type: "string",
    importance: "optional",
    required: false,
    description: "Forward / reverse shipment consignment ID.",
    sourceReports: ["returns"],
  },
  {
    key: "replacementOrderItemId",
    label: "Replacement Order Item ID",
    aliases: ["Replacement Order Item ID", "replacement_order_item_id", "Replacement Item ID"],
    type: "string",
    importance: "optional",
    required: false,
    description: "Item ID generated if customer requested an exchange/replacement.",
    sourceReports: ["returns"],
  },

  // 2. Product Information
  {
    key: "sku",
    label: "SKU",
    aliases: ["SKU", "sku", "Seller SKU", "Product SKU", "SKU ID"],
    type: "string",
    importance: "required",
    required: true,
    description: "Seller product SKU code.",
    sourceReports: ["returns"],
  },
  {
    key: "fsn",
    label: "FSN",
    aliases: ["FSN", "fsn", "Flipkart Serial Number", "Product FSN"],
    type: "string",
    importance: "optional",
    required: false,
    description: "Flipkart Serial Number catalog identifier.",
    sourceReports: ["returns"],
  },
  {
    key: "product",
    label: "Product Title",
    aliases: ["Product", "product", "Product Title", "Product Name", "Item Description"],
    type: "string",
    importance: "required",
    required: true,
    description: "Title of the returned product.",
    sourceReports: ["returns"],
  },
  {
    key: "totalPrice",
    label: "Total Price",
    aliases: ["Total Price", "total_price", "Item Value", "Price", "Amount"],
    type: "number",
    importance: "optional",
    required: false,
    description: "Billed sale price of the returned item.",
    sourceReports: ["returns"],
  },
  {
    key: "quantity",
    label: "Quantity",
    aliases: ["Quantity", "quantity", "Qty", "Units"],
    type: "integer",
    importance: "required",
    required: true,
    description: "Number of units returned in this request.",
    sourceReports: ["returns"],
  },
  {
    key: "ffType",
    label: "Fulfillment Type",
    aliases: ["FF Type", "ff_type", "Fulfillment Type", "Fulfilment"],
    type: "string",
    importance: "optional",
    required: false,
    description: "Fulfillment type (FA / Non-FA).",
    sourceReports: ["returns"],
  },

  // 3. Return Lifecycle Dates
  {
    key: "returnRequestedDate",
    label: "Return Requested Date",
    aliases: ["Return Requested Date", "return_requested_date", "Requested Date", "Return Date"],
    type: "date",
    importance: "required",
    required: false,
    description: "Date the customer or courier initiated the return request.",
    sourceReports: ["returns"],
  },
  {
    key: "returnApprovalDate",
    label: "Return Approval Date",
    aliases: ["Return Approval Date", "return_approval_date", "Approved Date"],
    type: "date",
    importance: "optional",
    required: false,
    description: "Date Flipkart approved the reverse pickup request.",
    sourceReports: ["returns"],
  },
  {
    key: "pickedUpDate",
    label: "Picked Up Date",
    aliases: ["Picked Up Date", "picked_up_date", "Pickup Date"],
    type: "date",
    importance: "optional",
    required: false,
    description: "Date the delivery agent picked up the returned item from customer.",
    sourceReports: ["returns"],
  },
  {
    key: "outForDeliveryDate",
    label: "Out For Delivery Date",
    aliases: ["Out For Delivery Date", "out_for_delivery_date", "OFD Date"],
    type: "date",
    importance: "optional",
    required: false,
    description: "Date reverse package was dispatched for doorstep return delivery.",
    sourceReports: ["returns"],
  },
  {
    key: "completedDate",
    label: "Completed Date",
    aliases: ["Completed Date", "completed_date", "Completion Date", "Return Complete Date"],
    type: "date",
    importance: "optional",
    required: false,
    description: "Date the return lifecycle completed and package was delivered to seller.",
    sourceReports: ["returns"],
  },
  {
    key: "returnDeliveryPromiseDate",
    label: "Return Delivery Promise Date",
    aliases: ["Return Delivery Promise Date", "return_delivery_promise_date", "Promise Date"],
    type: "date",
    importance: "optional",
    required: false,
    description: "SLA promise date for returning package back to seller.",
    sourceReports: ["returns"],
  },

  // 4. Return Classification & Status
  {
    key: "shipmentType",
    label: "Shipment Type",
    aliases: ["Shipment Type", "shipment_type", "Logistics Type"],
    type: "string",
    importance: "optional",
    required: false,
    description: "Forward or reverse shipment mode.",
    sourceReports: ["returns"],
  },
  {
    key: "returnStatus",
    label: "Return Status",
    aliases: ["Return Status", "return_status", "Status"],
    type: "string",
    importance: "required",
    required: true,
    description: "Operational transit status (start, in_transit, completed, cancelled).",
    sourceReports: ["returns"],
  },
  {
    key: "completionStatus",
    label: "Completion Status",
    aliases: ["Completion Status", "completion_status", "Resolution Status"],
    type: "string",
    importance: "optional",
    required: false,
    description: "Final outcome status of return package.",
    sourceReports: ["returns"],
  },
  {
    key: "returnType",
    label: "Return Type",
    aliases: ["Return Type", "return_type", "Type"],
    type: "string",
    importance: "required",
    required: true,
    description: "Customer return (RVP) vs Courier return (RTO).",
    sourceReports: ["returns"],
  },

  // 5. Reasons & Customer Comments
  {
    key: "returnReason",
    label: "Return Reason",
    aliases: ["Return Reason", "return_reason", "Reason", "Primary Reason"],
    type: "string",
    importance: "required",
    required: true,
    description: "Primary reason selected for returning the item.",
    sourceReports: ["returns"],
  },
  {
    key: "returnSubReason",
    label: "Return Sub-reason",
    aliases: ["Return Sub-reason", "return_sub_reason", "Sub-reason", "Sub Reason"],
    type: "string",
    importance: "optional",
    required: false,
    description: "Granular sub-reason explaining specific defect or dissatisfaction.",
    sourceReports: ["returns"],
  },
  {
    key: "comments",
    label: "Customer / Inspection Comments",
    aliases: [
      "Comments",
      "comments",
      "Customer Comments",
      "Remarks",
      "Customer Remarks",
      "Inspection Comments",
    ],
    type: "string",
    importance: "required",
    required: false,
    description: "Direct verbatim customer remarks and hub inspection notes. Never dropped.",
    sourceReports: ["returns"],
  },

  // 6. Vendor & Warehouse
  {
    key: "vendorName",
    label: "Vendor Name",
    aliases: ["Vendor Name", "vendor_name", "Vendor", "Seller Name"],
    type: "string",
    importance: "optional",
    required: false,
    description: "Seller registered name.",
    sourceReports: ["returns"],
  },
  {
    key: "locationName",
    label: "Location Name",
    aliases: ["Location Name", "location_name", "Warehouse Name", "Hub Name"],
    type: "string",
    importance: "optional",
    required: false,
    description: "Destination warehouse location name.",
    sourceReports: ["returns"],
  },

  // 7. Packaging & Verification
  {
    key: "flyerStatus",
    label: "Flyer Status",
    aliases: ["Flyer Status", "flyer_status"],
    type: "string",
    importance: "informational",
    required: false,
    description: "Security flyer seal status.",
    sourceReports: ["returns"],
  },
  {
    key: "flyerCaptured",
    label: "Flyer Captured",
    aliases: ["Flyer Captured", "flyer_captured"],
    type: "string",
    importance: "informational",
    required: false,
    description: "Security flyer barcode captured at pickup.",
    sourceReports: ["returns"],
  },
  {
    key: "flyerActual",
    label: "Flyer Actual",
    aliases: ["Flyer Actual", "flyer_actual"],
    type: "string",
    importance: "informational",
    required: false,
    description: "Actual flyer barcode scanned at destination.",
    sourceReports: ["returns"],
  },
  {
    key: "deliveryProofTime",
    label: "Delivery Proof Time",
    aliases: ["Delivery Proof Time", "delivery_proof_time", "POD Time"],
    type: "string",
    importance: "informational",
    required: false,
    description: "Timestamp proof of doorstep return delivery.",
    sourceReports: ["returns"],
  },
  {
    key: "obdEligible",
    label: "OBD Eligible",
    aliases: ["OBD Eligible", "obd_eligible"],
    type: "string",
    importance: "informational",
    required: false,
    description: "Open Box Delivery eligibility.",
    sourceReports: ["returns"],
  },
  {
    key: "obdStatus",
    label: "OBD Status",
    aliases: ["OBD Status", "obd_status"],
    type: "string",
    importance: "informational",
    required: false,
    description: "Open Box Delivery verification status.",
    sourceReports: ["returns"],
  },
  {
    key: "obdRemarks",
    label: "OBD Remarks",
    aliases: ["OBD Remarks", "obd_remarks"],
    type: "string",
    importance: "informational",
    required: false,
    description: "Remarks recorded during open box inspection.",
    sourceReports: ["returns"],
  },
  {
    key: "deliveryProofOtc",
    label: "Delivery Proof OTC",
    aliases: ["Delivery Proof OTC", "delivery_proof_otc", "OTP Verified"],
    type: "string",
    importance: "informational",
    required: false,
    description: "One Time Code confirmation at handover.",
    sourceReports: ["returns"],
  },
  {
    key: "bagTrackingId",
    label: "Bag Tracking ID",
    aliases: ["Bag Tracking ID", "bag_tracking_id"],
    type: "string",
    importance: "informational",
    required: false,
    description: "Logistics consolidated bag tracking identifier.",
    sourceReports: ["returns"],
  },

  // 8. Order & B2B Invoicing
  {
    key: "orderType",
    label: "Order Type",
    aliases: ["Order Type", "order_type", "Payment Type"],
    type: "string",
    importance: "optional",
    required: false,
    description: "PREPAID or COD order classification.",
    sourceReports: ["returns"],
  },
  {
    key: "customerGstin",
    label: "Customer GSTIN",
    aliases: ["Customer GSTIN", "customer_gstin", "GSTIN"],
    type: "string",
    importance: "optional",
    required: false,
    description: "Customer business GST identification number for B2B returns.",
    sourceReports: ["returns"],
  },
  {
    key: "customerCompanyName",
    label: "Customer Company Name",
    aliases: ["Customer Company Name", "customer_company_name", "Company Name"],
    type: "string",
    importance: "optional",
    required: false,
    description: "B2B business purchaser entity name.",
    sourceReports: ["returns"],
  },
  {
    key: "irnNumber",
    label: "IRN Number",
    aliases: ["IRN Number", "irn_number", "Invoice Reference Number", "IRN"],
    type: "string",
    importance: "optional",
    required: false,
    description: "Government E-invoice Invoice Reference Number.",
    sourceReports: ["returns"],
  },
  {
    key: "invoiceNumber",
    label: "Invoice Number",
    aliases: ["Invoice Number", "invoice_number", "Tax Invoice Number", "Invoice No"],
    type: "string",
    importance: "optional",
    required: false,
    description: "Original sales invoice number issued for order.",
    sourceReports: ["returns"],
  },
  {
    key: "invoiceDate",
    label: "Invoice Date",
    aliases: ["Invoice Date", "invoice_date", "Date of Invoice"],
    type: "date",
    importance: "optional",
    required: false,
    description: "Date sales tax invoice was issued.",
    sourceReports: ["returns"],
  },

  // 9. Return Results & Condition
  {
    key: "returnResult",
    label: "Return Result",
    aliases: ["Return Result", "return_result", "Result"],
    type: "string",
    importance: "optional",
    required: false,
    description: "Outcome of return inspection (accepted, rejected, damaged).",
    sourceReports: ["returns"],
  },
  {
    key: "returnCompletionType",
    label: "Return Completion Type",
    aliases: ["Return Completion Type", "return_completion_type"],
    type: "string",
    importance: "optional",
    required: false,
    description: "Standard delivery, replacement, or scrap disposition.",
    sourceReports: ["returns"],
  },
  {
    key: "finalCondition",
    label: "Final Condition",
    aliases: [
      "Final Condition of Returned Product",
      "Final Condition",
      "final_condition",
      "Product Condition",
      "Condition",
    ],
    type: "string",
    importance: "optional",
    required: false,
    description: "Graded condition of returned merchandise (intact, seal broken, damaged, missing).",
    sourceReports: ["returns"],
  },
  {
    key: "returnCompletionBreach",
    label: "Return Completion Breach",
    aliases: ["Return Completion Breach", "return_completion_breach", "SLA Breach"],
    type: "string",
    importance: "optional",
    required: false,
    description: "Indicator if return delivery breached Flipkart SLA commitment.",
    sourceReports: ["returns"],
  },
  {
    key: "returnCancellationDate",
    label: "Return Cancellation Date",
    aliases: ["Return Cancellation Date", "return_cancellation_date"],
    type: "date",
    importance: "optional",
    required: false,
    description: "Date customer or courier cancelled return request.",
    sourceReports: ["returns"],
  },
  {
    key: "returnCancellationReason",
    label: "Return Cancellation Reason",
    aliases: ["Return Cancellation Reason", "return_cancellation_reason"],
    type: "string",
    importance: "optional",
    required: false,
    description: "Reason return request was cancelled prior to completion.",
    sourceReports: ["returns"],
  },
];
