"use client";

import React, { useState } from "react";
import { useExcelData } from "@/context/excel-context";
import {
  getTopProductsBySales,
  getTopProductsByEarnings,
  getTopProductsByUnits,
  getTopProductsByCustomerReturns,
  getTopProductsByCancellations,
  getTopProductsByRto,
} from "../calculations/products";
import { ChartCardContainer } from "../charts/chart-container";
import { HorizontalBarChart } from "../charts/horizontal-bar-chart";
import { TopNSelect } from "../components/top-n-select";
import { MissingReportBanner } from "../components/missing-report-banner";
import { TopNCount } from "../types/analytics.types";

export function ProductsView() {
  const { pnlReport, records } = useExcelData();
  const [topN, setTopN] = useState<TopNCount>(10);

  const hasPnl = Boolean(pnlReport && pnlReport.skuLevel.length > 0);
  const hasReturns = Boolean(records && records.length > 0);

  if (!hasPnl && !hasReturns) {
    return (
      <MissingReportBanner
        reportRequired="both"
        featureTitle="Product Analytics"
        benefits={[
          "Product revenue and unit sales volumes",
          "Customer Returns (RVP) by product title",
          "Logistics Returns (RTO) distribution",
          "Order cancellations per product",
        ]}
      />
    );
  }

  const skus = pnlReport?.skuLevel || [];
  const topSales = getTopProductsBySales(pnlReport, records, topN);
  const topEarnings = getTopProductsByEarnings(pnlReport, topN);
  const topUnits = getTopProductsByUnits(pnlReport, records, topN);
  const topCustomerReturns = getTopProductsByCustomerReturns(skus, topN);
  const topCancellations = getTopProductsByCancellations(skus, topN);
  const topRto = getTopProductsByRto(skus, topN);

  return (
    <div className="space-y-6">
      {/* Top Filter Bar */}
      <div className="flex items-center justify-between p-3.5 rounded-xl border border-border bg-card shadow-2xs">
        <span className="text-xs font-semibold text-foreground">
          Top {topN} Products by Catalog Performance
        </span>
        <TopNSelect value={topN} onChange={setTopN} />
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Chart 1: Top Products by Sales */}
        <ChartCardContainer
          title="Top Products by Net Sales"
          description="Total billed revenue generated by each product catalog item."
          badge="Sales"
        >
          <HorizontalBarChart data={topSales} barColor="var(--chart-1)" />
        </ChartCardContainer>

        {/* Chart 2: Top Products by Net Earnings */}
        {hasPnl && (
          <ChartCardContainer
            title="Top Products by Net Earnings"
            description="Net profit realized after deducting all marketplace expenses and taxes."
            badge="Earnings"
          >
            <HorizontalBarChart data={topEarnings} barColor="var(--chart-2)" />
          </ChartCardContainer>
        )}

        {/* Chart 3: Top Products by Units */}
        <ChartCardContainer
          title="Top Products by Ordered Units"
          description="Total volume of units sold across the catalog."
          badge="Volume"
        >
          <HorizontalBarChart data={topUnits} barColor="var(--chart-3)" />
        </ChartCardContainer>

        {/* Chart 4: Customer Returns (RVP) */}
        {hasPnl && (
          <ChartCardContainer
            title="Top Products by Customer Returns (RVP)"
            description="Units returned directly by customers due to defects, sizing, or remorse."
            badge="Customer Returns"
          >
            <HorizontalBarChart data={topCustomerReturns} barColor="var(--chart-5)" />
          </ChartCardContainer>
        )}

        {/* Chart 5: Cancellations */}
        {hasPnl && (
          <ChartCardContainer
            title="Top Products by Cancellations"
            description="Orders cancelled before doorstep delivery."
            badge="Cancellations"
          >
            <HorizontalBarChart data={topCancellations} barColor="var(--chart-4)" />
          </ChartCardContainer>
        )}

        {/* Chart 6: Logistics Returns (RTO) */}
        {hasPnl && (
          <ChartCardContainer
            title="Top Products by Logistics Returns (RTO)"
            description="Undelivered courier returns returned back to seller warehouse."
            badge="Courier RTO"
          >
            <HorizontalBarChart data={topRto} barColor="var(--chart-2)" />
          </ChartCardContainer>
        )}
      </div>
    </div>
  );
}
